---
title: "MSiA400_LabAssignment1"
output:
  pdf_document: default
  html_document: default
---

setwd("~/Desktop/Everything Starts With Data/Lab Assignment 1")

#Problem 1
##a)
```{r}
markov = read.table("markov100.txt", header=FALSE)
P = as.matrix(markov)
a <- c(1,rep(0,99))
library(expm)
p_10 <- a %*% (P %^% 10)	
p_10[1,5]
```

##b)
```{r}
a1 <- c(rep(1/3,3),rep(0,97))
p1_10 <- a1 %*% (P %^% 10)
p1_10[1,10]
```

##c)
```{r}
Q <- t(P) - diag(100)
Q[100,] <- c(rep(1,100))
rhs <- c(rep(0,99),1)
Pi = solve(Q) %*% rhs
Pi[1,1]
```

##d)
```{r}
B <- P[1:99,1:99]
Q <- diag(99) - B
e <- c(rep(1,99))
m <- solve(Q) %*% e
m[1,1]
```

#Problem 2
##a)
```{r}
webtraffic = read.table("webtraffic.txt", header=TRUE)
sum <- colSums(webtraffic)
Traffic <- t(matrix(sum, nrow = 9, ncol = 9))
Traffic
```

##b)
```{r}
Traffic[9,1] <- 1000
P_traffic <- Traffic/rowSums(Traffic)
P_traffic
```

##c)
```{r}
Q_traffic = t(P_traffic) - diag(9)
Q_traffic[9,] = c(1,1,1,1,1,1,1,1,1)
rhs_traffic = c(0,0,0,0,0,0,0,0,1)
Pi_traffic = solve(Q_traffic) %*% rhs_traffic
Pi_traffic
```

##d)
```{r}
B_traffic = P_traffic[1:8,1:8]
Q_traffic1 = diag(8) - B_traffic
e_traffic = c(1,1,1,1,1,1,1,1)
m_traffic = solve(Q_traffic1) %*% e_traffic
time <- c(0.1,2,3,5,5,3,3,2,0)
avg_time <- time %*% Pi_traffic 
spend_time = colSums(m_traffic) * avg_time
spend_time
```

##e)
```{r}
new_traffic <- Traffic
new_traffic[2,6] = new_traffic[2,3] * 0.3
new_traffic[2,7] = new_traffic[2,4] * 0.2
new_traffic[2,3] = new_traffic[2,3] * 0.7
new_traffic[2,4] = new_traffic[2,4] * 0.8
new_traffic[9,1] = 1000
P_newtraffic <- new_traffic/rowSums(new_traffic)
Q_newtraffic = t(P_newtraffic) - diag(9)
Q_newtraffic[9,] = c(1,1,1,1,1,1,1,1,1)
rhs_newtraffic = c(0,0,0,0,0,0,0,0,1)
Pi_newtraffic = solve(Q_newtraffic) %*% rhs_newtraffic
Pi_newtraffic
Pi_newtraffic - Pi_traffic
```

Compared to Pi, chances to visit Page 2 and Page 3 in Pi2 decreases. The link works.
